const LEVELS=[
{id:'01',title:'SIGNAL',brief:'Make the terminal true. One switch is enough.',budget:1,par:1,nodes:[I('A','A',false,12,48),I('B','B',false,12,76),R('X','A XOR B','xor',['A','B'],true,66,62)]},
{id:'02',title:'CONSENSUS',brief:'A conjunction accepts only unanimous signals.',budget:2,par:2,nodes:[I('A','A',false,12,48),I('B','B',false,12,76),R('X','A AND B','and',['A','B'],true,66,62)]},
{id:'03',title:'NEGATION',brief:'The observation must become false.',budget:1,par:1,nodes:[I('A','SOURCE',false,12,62),R('X','NOT A','not',['A'],false,66,62)]},
{id:'04',title:'PARITY',brief:'Change one premise. Preserve an odd number of true signals.',budget:1,par:1,nodes:[I('A','A',true,10,36),I('B','B',true,10,62),I('C','C',false,10,88),R('P','A XOR B','xor',['A','B'],null,48,48),R('X','P XOR C','xor',['P','C'],true,76,68)]},
{id:'05',title:'AXIOM',brief:'Three observations. Three simultaneous constraints. Find the only stable world.',budget:3,par:3,nodes:[I('A','A',false,8,32),I('B','B',false,8,62),I('C','C',false,8,92),R('D','A XOR B','xor',['A','B'],false,63,32),R('E','B AND C','and',['B','C'],true,63,62),R('F','NOT A','not',['A'],false,63,92)]}
];
function I(id,label,initial,x,y){return{id,label,kind:'input',initial,x,y}}function R(id,label,kind,deps,target,x,y){return{id,label,kind,deps,target,x,y}}
let page=location.hash==='#play'?'play':'title',levelIndex=0,moves=0,inputs={},pulse=[];
function startInputs(l){return Object.fromEntries(l.nodes.filter(n=>n.kind==='input').map(n=>[n.id,!!n.initial]))}
function valuesFor(l){let v={...inputs};for(let p=0;p<l.nodes.length;p++)for(const n of l.nodes){if(n.kind==='input')continue;const d=n.deps.map(id=>!!v[id]);if(n.kind==='not')v[n.id]=!d[0];if(n.kind==='and')v[n.id]=d.every(Boolean);if(n.kind==='xor')v[n.id]=d.filter(Boolean).length%2===1}return v}
function faults(l,v){return l.nodes.filter(n=>typeof n.target==='boolean'&&v[n.id]!==n.target)}
function chrome(inner,l,m){return`<main class="shell"><header class="topline"><span>AXIOM / LOGICAL INSTRUMENT</span><span>CASE ${String(l).padStart(2,'0')} · MOVE ${String(m).padStart(2,'0')}</span></header>${inner}<footer class="footerline"><span>LOCAL SYSTEM</span><span>NO NETWORK · NO AI</span></footer></main>`}
function title(){return chrome(`<section class="title-stage"><div class="serial">INSTRUMENT 01<br>REVISION A</div><div class="mark" aria-hidden="true"><i></i><i></i><i></i><i></i></div><div class="title-copy"><p class="eyebrow">A STUDY IN CONSISTENCY</p><h1>AXIOM</h1><p class="dek">Every statement changes the system.<br>Leave no contradiction behind.</p><button class="enter" data-start>BEGIN CALIBRATION <span>↗</span></button></div><div class="index"><span>5 CASES</span><span>FINITE MOVES</span><span>ONE STABLE WORLD</span></div></section>`,0,0)}
function network(l,v){const edges=l.nodes.flatMap(n=>(n.deps||[]).map(id=>({a:l.nodes.find(x=>x.id===id),b:n})));return`<div class="network"><svg class="wires" viewBox="0 0 100 120" preserveAspectRatio="none">${edges.map(e=>`<line x1="${e.a.x+8}" y1="${e.a.y}" x2="${e.b.x-2}" y2="${e.b.y}" class="${v[e.a.id]?'hot':''}"/>`).join('')}</svg>${l.nodes.map(n=>{const bad=typeof n.target==='boolean'&&v[n.id]!==n.target,cls=['node',n.kind==='input'?'premise':'rule',v[n.id]?'true':'false',bad?'bad':'',pulse.includes(n.id)?'pulse':''].filter(Boolean).join(' '),inside=`<span class="node-id">${n.id}</span><span class="node-label">${n.label}</span><span class="node-value">${v[n.id]?1:0}</span>${typeof n.target==='boolean'?`<span class="target">REQ ${n.target?1:0}</span>`:''}`;return n.kind==='input'?`<button class="${cls}" style="left:${n.x}%;top:${n.y}%" data-toggle="${n.id}" aria-label="Toggle ${n.label}">${inside}</button>`:`<div class="${cls}" style="left:${n.x}%;top:${n.y}%">${inside}</div>`}).join('')}</div>`}
function game(){const l=LEVELS[levelIndex],v=valuesFor(l),bad=faults(l,v),solved=!bad.length,score=solved?Math.max(100,1000-(moves-l.par)*150):0;return chrome(`<section class="case-head"><div><p class="eyebrow">CASE ${l.id} / 05</p><h2>${l.title}</h2></div><p>${l.brief}</p><div class="meter"><span>MOVES</span><b>${moves}/${l.budget}</b></div></section><section class="board ${solved?'is-solved':''}"><div class="ruler left">01<br>02<br>03<br>04<br>05</div>${network(l,v)}<aside class="audit"><p class="eyebrow">LIVE AUDIT</p><div class="status ${solved?'stable':'conflict'}"><i></i>${solved?'STABLE':'CONTRADICTION'}</div><dl><div><dt>RULES</dt><dd>${l.nodes.filter(n=>n.kind!=='input').length}</dd></div><div><dt>FAULTS</dt><dd>${bad.length}</dd></div><div><dt>PAR</dt><dd>${l.par}</dd></div></dl><p class="audit-note">${solved?'All required observations agree. The system can be certified.':bad.map(n=>`${n.id} EXPECTED ${n.target?1:0}`).join(' · ')}</p></aside></section><section class="command"><button class="text-button" data-reset>↺ RESET CASE</button><div class="legend"><span><i class="swatch premise"></i>PREMISE</span><span><i class="swatch rule"></i>RULE</span><span><i class="swatch fault"></i>FAULT</span></div>${solved?`<div class="result"><span>CERTIFIED</span><b>${String(score).padStart(4,'0')}</b>${levelIndex<4?'<button data-next>NEXT CASE →</button>':''}</div>`:moves>=l.budget?'<button class="advance" data-reset>NO MOVES · RETRY →</button>':'<span class="hint">Select a square premise.</span>'}</section>`,levelIndex+1,moves)}
function reset(next=levelIndex){levelIndex=next;moves=0;inputs=startInputs(LEVELS[levelIndex]);pulse=[];render()}
function render(){document.getElementById('app').innerHTML=page==='title'?title():game();bind()}
function bind(){document.querySelector('[data-start]')?.addEventListener('click',()=>{page='play';location.hash='play';reset(0)});document.querySelectorAll('[data-toggle]').forEach(b=>b.addEventListener('click',()=>{const l=LEVELS[levelIndex],v=valuesFor(l);if(moves>=l.budget||!faults(l,v).length)return;const id=b.dataset.toggle;inputs[id]=!inputs[id];moves++;pulse=l.nodes.filter(n=>n.id===id||(n.deps||[]).includes(id)).map(n=>n.id);render();setTimeout(()=>{pulse=[];render()},650)}));document.querySelectorAll('[data-reset]').forEach(b=>b.addEventListener('click',()=>reset()));document.querySelector('[data-next]')?.addEventListener('click',()=>reset(levelIndex+1))}
addEventListener('hashchange',()=>{page=location.hash==='#play'?'play':'title';if(page==='play'&&!Object.keys(inputs).length)inputs=startInputs(LEVELS[0]);render()});render();
